/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tanner_production.ui;

import tanner_production.Constants;

/**
 *
 * @author t7emon
 */
public class JFrame extends javax.swing.JFrame {

    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label = new javax.swing.JLabel();
        TanGreenDhide_CheckBox = new javax.swing.JCheckBox();
        TanBlueDhide_CheckBox = new javax.swing.JCheckBox();
        TanRedDhide_CheckBox = new javax.swing.JCheckBox();
        TanBlackDhide_CheckBox = new javax.swing.JCheckBox();
        Start_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Label.setText("                          null's Simple D'hide Tanner");

        TanGreenDhide_CheckBox.setText("Tan Green D'hide");
        TanGreenDhide_CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TanGreenDhide_CheckBoxActionPerformed(evt);
            }
        });

        TanBlueDhide_CheckBox.setText("Tan Blue D'hide");
        TanBlueDhide_CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TanBlueDhide_CheckBoxActionPerformed(evt);
            }
        });

        TanRedDhide_CheckBox.setText("Tan Red D'hide");
        TanRedDhide_CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TanRedDhide_CheckBoxActionPerformed(evt);
            }
        });

        TanBlackDhide_CheckBox.setText("Tan Black D'hide");
        TanBlackDhide_CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TanBlackDhide_CheckBoxActionPerformed(evt);
            }
        });

        Start_Button.setText("Start");
        Start_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Start_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TanRedDhide_CheckBox)
                            .addComponent(TanBlackDhide_CheckBox)
                            .addComponent(TanBlueDhide_CheckBox)
                            .addComponent(TanGreenDhide_CheckBox)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(Start_Button)))
                .addContainerGap(121, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Label)
                .addGap(14, 14, 14)
                .addComponent(TanGreenDhide_CheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TanBlueDhide_CheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TanRedDhide_CheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TanBlackDhide_CheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Start_Button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TanGreenDhide_CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TanGreenDhide_CheckBoxActionPerformed
        Constants.tan_Green_dragonhide = true;
        TanBlueDhide_CheckBox.setSelected(false);
        TanRedDhide_CheckBox.setSelected(false);
        TanBlackDhide_CheckBox.setSelected(false);
    }//GEN-LAST:event_TanGreenDhide_CheckBoxActionPerformed

    private void TanBlueDhide_CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TanBlueDhide_CheckBoxActionPerformed
        Constants.tan_Blue_dragonhide = true;
        TanGreenDhide_CheckBox.setSelected(false);
        TanRedDhide_CheckBox.setSelected(false);
        TanBlackDhide_CheckBox.setSelected(false);
    }//GEN-LAST:event_TanBlueDhide_CheckBoxActionPerformed

    private void TanRedDhide_CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TanRedDhide_CheckBoxActionPerformed
        Constants.tan_Red_dragonhide = true;
        TanGreenDhide_CheckBox.setSelected(false);
        TanBlueDhide_CheckBox.setSelected(false);
        TanBlackDhide_CheckBox.setSelected(false);
    }//GEN-LAST:event_TanRedDhide_CheckBoxActionPerformed

    private void TanBlackDhide_CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TanBlackDhide_CheckBoxActionPerformed
        Constants.tan_Black_dragonhide = true;
        TanGreenDhide_CheckBox.setSelected(false);
        TanBlueDhide_CheckBox.setSelected(false);
        TanRedDhide_CheckBox.setSelected(false);
    }//GEN-LAST:event_TanBlackDhide_CheckBoxActionPerformed

    private void Start_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Start_ButtonActionPerformed
        Constants.start = true;
        this.dispose();
        this.setVisible(false);
    }//GEN-LAST:event_Start_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label;
    private javax.swing.JButton Start_Button;
    private javax.swing.JCheckBox TanBlackDhide_CheckBox;
    private javax.swing.JCheckBox TanBlueDhide_CheckBox;
    private javax.swing.JCheckBox TanGreenDhide_CheckBox;
    private javax.swing.JCheckBox TanRedDhide_CheckBox;
    // End of variables declaration//GEN-END:variables
}
